### ISSUE TITLE
Error while clicking on the plugin with any game

### ISSUE THREAD

**Issue by Parfaitement** [fattard/MissingEventFlagsCheckerPlugin#7]
A fatal non-Ul error has occurred in PKHeX, and there was a problem
displaying the details. Please report this to the author.

Thinking about a compatibility error, using latest PKHeX available here: 
https://github.com/architdate/PKHeX-Plugins/wiki/Installing-PKHeX-Plugins#manual-installation-or-installing-older-releases

**Comment by fattard** [comment]
Hello, there are no known compatibility issues between latest version of PKHeX (27.07.24) and the plugin version 0.8.2.
Ensure you downloaded and placed the correct plugin version in the 'plugins' folder, and that no other copies of it exists.

If unsure, remove all plugins and reinstall them, one by one.

**Comment by fattard** [comment]
Improved 'setup instructions'.
Please, use latest PKHeX version.
